- name: "Installing packages with loops"
  hosts: all
  become: yes
  vars:
    rambabu:
    - git
    - nginx
    - htop
    - vim
  tasks:
    - name: installing packages
      ansible.builtin.package:
        name: "{{ item }}"
      loop: "{{ rambabu }}"
      notify: restart nginx
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

