- name: install and start sshd with handler
  hosts: db
  become: yes
  tasks:
    - name: install nginx
      yum:
        name: nginx
        state: present
      notify: restart nginx 

    - name: sshd config
      copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config 
      notify: restart sshd

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart sshd
      service:
        name: sshd
        state: restarted

