- name: testing prompt variable
  hosts: local
  connection: local
  vars_prompt:
    - name: "username"
      prompt: please enter your user name
      private: false

    - name: password
      prompt: whats your password
      private: true
  tasks:
  - name: print both username and password
    ansible.builtin.debug:
      msg: "user name is: {{ username }}, password is: {{ password }}"


