#!/bin/bash

# Create project structure
mkdir -p mini_ansible_project/{playbooks,templates,vars}

# Inventory
cat > mini_ansible_project/inventory << 'EOF'
[all]
localhost ansible_connection=local
EOF

# Vars
cat > mini_ansible_project/vars/common_vars.yml << 'EOF'
common_packages:
  - git
  - htop
  - nginx

users:
  - name: devuser
    uid: 1500
  - name: testuser
    uid: 1501

app_port: 8080
EOF

# Template
cat > mini_ansible_project/templates/app.conf.j2 << 'EOF'
# Application configuration template
# Generated by Ansible

[app]
port = {{ app_port }}
log_level = INFO
EOF

# Playbooks
cat > mini_ansible_project/playbooks/01_gather_facts.yml << 'EOF'
- name: Gather facts and detect OS
  hosts: all
  become: yes
  tasks:
    - name: Gather all facts
      ansible.builtin.setup:

    - name: Print OS family
      ansible.builtin.debug:
        msg: "OS family is {{ ansible_facts['os_family'] }}"
EOF

cat > mini_ansible_project/playbooks/02_install_packages.yml << 'EOF'
- name: Install multiple packages with loop
  hosts: all
  become: yes
  vars_files:
    - ../vars/common_vars.yml
  tasks:
    - name: Install common packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ common_packages }}"
      notify: restart nginx_if_installed

  handlers:
    - name: restart nginx_if_installed
      ansible.builtin.service:
        name: nginx
        state: restarted
EOF

cat > mini_ansible_project/playbooks/03_conditional_os.yml << 'EOF'
- name: Conditional tasks based on OS
  hosts: all
  become: yes
  tasks:
    - name: RedHat-specific task
      ansible.builtin.debug:
        msg: "This is RedHat system"
      when: ansible_facts['os_family'] == "RedHat"

    - name: Debian-specific task
      ansible.builtin.debug:
        msg: "This is Debian system"
      when: ansible_facts['os_family'] == "Debian"
EOF

cat > mini_ansible_project/playbooks/04_template_deploy.yml << 'EOF'
- name: Deploy configuration using template
  hosts: all
  become: yes
  vars_files:
    - ../vars/common_vars.yml
  tasks:
    - name: Copy app config template
      ansible.builtin.template:
        src: templates/app.conf.j2
        dest: /tmp/app.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart myapp

  handlers:
    - name: restart myapp
      ansible.builtin.service:
        name: myapp
        state: restarted
EOF

cat > mini_ansible_project/playbooks/05_user_management.yml << 'EOF'
- name: Create multiple users
  hosts: all
  become: yes
  vars_files:
    - ../vars/common_vars.yml
  tasks:
    - name: Create users
      ansible.builtin.user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        state: present
        shell: /bin/bash
      loop: "{{ users }}"
EOF

cat > mini_ansible_project/playbooks/06_file_directory.yml << 'EOF'
- name: Simple file creation and content copy
  hosts: all
  become: yes
  tasks:
    - name: Create directory
      ansible.builtin.file:
        path: /tmp/testdir
        state: directory

    - name: Create file with content
      ansible.builtin.copy:
        content: "This is a test file\nCreated by Ansible"
        dest: /tmp/testdir/testfile.txt
        mode: '0644'
EOF

echo "✅ mini_ansible_project created successfully!"
